### PR TITLE
Update io.github.mak448a.QTCord.yml

### PR DESCRIPTION
**Pull request by mak448a**

### CODE REVIEW

**Comment by hfiguiere** [comment]
```
io.github.mak448a.QTCord:          AppData problem: tag-invalid : <release> versions are not in order [v0.0.2 before v0.0.4]
```

**Comment by hfiguiere** [comment]
this is the error.

**Comment by mak448a** [comment]
> this is the error.

Where do I find these errors for next time?

**Comment by hfiguiere** [comment]
it's all in the build log 

https://buildbot.flathub.org/#/builders/6/builds/89795

**Pull request merged**
