### PR TITLE
Little updates

### PR DESCRIPTION
**Pull request by mak448a**
Adding little things like app categories, and other stuff.

### CODE REVIEW

**Comment by mak448a** [comment]
Sorry to bother you, but do you know what this error means? ```
Errors were raised during this compose run:
io.github.mak448a.QTCord
  E: no-valid-category
general
  E: filters-but-no-output```
I know what the no valid category means, but have no idea what filters-but-no-output means.
@bbhtt

**Comment by bbhtt** [comment]
Second one is due to first one, your desktop file is missing categories

image


But the one here has them https://github.com/mak448a/QTCord/blob/main/src/io.github.mak448a.QTCord.desktop so you just need to update the app release or commit

**Comment by mak448a** [comment]
Thanks, I'm doing that now.

**Comment by mak448a** [comment]
bot, build io.github.mak448a.QTCord

**Comment by mak448a** [comment]
bot, build io.github.mak448a.QTCord

**Comment by mak448a** [comment]
bot, build io.github.mak448a.QTCord

**Pull request merged**
